const projects = [{ type: "website", 
                    name: "Project 1", 
                    languages: ["html", "css", "javascript"], 
                    description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                    setup: "VScode version ___", 
                    imgURL: "images\other\placeholderImage.png",
                    githubURL: "https://github.com/Obemegargel/wdd131" },

                    { type: "website", 
                        name: "Project 2", 
                        languages: ["html", "css", "javascript"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "VScode version ___", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },

                    { type: "website", 
                        name: "Project 3", 
                        languages: ["html", "css", "javascript"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "VScode version ___", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },
                    
                    { type: "app", 
                        name: "Project 4", 
                        languages: ["kotlin"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "Intellij IDEA community version ___", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },

                    { type: "app", 
                        name: "Project 5", 
                        languages: ["kotlin","python"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "Intellij IDEA community version ___", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },
                    
                    { type: "app", 
                        name: "Project 6", 
                        languages: ["kotlin"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "Intellij IDEA community version ___", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },

                    { type: "ai", 
                        name: "Project 7", 
                        languages: ["pyspark","python"], 
                        description: "apsodfijpofi jfpoaidfasdpofn dasfpi asdfndslkfjashdfidsjnfa spdfjasnfpasdjfndaspfjdas fnasdkf jnasdfjsndafnasdp ifnasdfijsn dfpisdnfsadi fnsadpfdspifdsnfd", 
                        setup: "DataBricks", 
                        imgURL: "images\other\placeholderImage.png",
                        githubURL: "https://github.com/Obemegargel/wdd131" },
]

export default projects